# Generated by Django 6.0.3 on 2026-04-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_alter_tweet_updated_at_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p_img',
            field=models.ImageField(blank=True, default='photos/default_profile.jpg', null=True, upload_to='photos/'),
        ),
    ]
