# Generated by Django 6.0.4 on 2026-04-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_alter_profile_p_img_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
